version: '3.3'

services:
  nginx_api:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/srv/app/public:ro
    ports:
      - "80:80"
      - "443:443"
    links:
      - node_api
    depends_on:
      - node_api
    networks:
      - nesjs-network

  node_api:
    env_file:
      - .env
    build: .
    command: npm run start:debug
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "${APP_DEBUG_PORT}:${APP_DEBUG_PORT}"
    networks:
      - nesjs-network
    volumes:
      - .:/srv/app
      - /node_modules
    depends_on:
      - mariadb_api
    links:
      - mariadb_api
    restart: always

  mariadb_api:
    restart: on-failure
    image: mariadb:latest
    env_file:
      - .env
    volumes:
      - mariadb_volume_api:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - nesjs-network

volumes:
  mariadb_volume_api:
  node_modules:

networks:
  nesjs-network:
    external: true
