services:
  app:
    build:
      context: .
    command: npm run start
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
    volumes:
      - .:/srv/app:rw,cached
      - ./public:/public:rw,cached
    env_file:
      - .env

  db:
    build:
      context: ./docker/mariadb
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/public:r,cached
      - ./docker/nginx/index.html:/usr/share/nginx/html/index.html
      - ./docker/nginx/privacy-policy.html:/usr/share/nginx/html/privacy-policy.html
    depends_on:
      - app